# Generated by Django 4.1.7 on 2023-03-10 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='ph',
        ),
    ]
